name: Pull Request Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: "dummy-key-for-testing"
      STREAM_API_KEY: "dummy-stream-key"
      STREAM_API_SECRET: "dummy-stream-secret"
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.7.1
          
      - name: Install API service dependencies
        working-directory: ./src/api
        run: poetry install --with test
        
      - name: Run black
        working-directory: ./src/api
        run: poetry run black . --check
        
      - name: Run flake8
        working-directory: ./src/api
        run: |
          poetry run flake8 app/ tests/ \
            --exclude=.git,__pycache__,.venv,build,dist \
            --max-line-length=88 \
            --extend-ignore=E203,W503
        
      - name: Run API tests
        working-directory: ./src/api
        run: poetry run pytest 